import { Inter } from 'next/font/google'
import './globals.css'
import { MainDataFunc } from './Context/MainFormDataContext'



const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <MainDataFunc>
      <body className={inter.className}>
        <header className='p-11 bg-slate-800'></header>
          {children} 
          <footer className='bg-zinc-700 p-11'></footer>    
        </body>
      </MainDataFunc>
    </html>
  )
}
